### ISSUE TITLE
Edit player profile - use save/close buttons like edit character

### ISSUE THREAD

**Issue by therealadamstel** [tyejae/msf-gg-beta-test#20]
Mostly just a consistency issue. Would also be nice to have some color differentiation so Save is more obviously the more important button (not green/red for the poor color blind folks, but if Close was gray and Save was blue I think it would be obvious).

**Comment by tyejae** [comment]
Done
![image](https://user-images.githubusercontent.com/6165105/61426697-29d50100-a8d0-11e9-96c0-5e9b2ebf8e93.png)
