### ISSUE TITLE
Failure banner shows momentarily even after a successful action

### ISSUE THREAD

**Issue by therealadamstel** [tyejae/msf-gg-beta-test#22]
After saving a character, and the green success banner shows, when it disappears, the red failure banner is there for a split second. it made me think something wrong had happened at first.

It looks like the script is closing the success banner (display:none) and then fading out either what contains them both or fading out the failure banner.

**Comment by tyejae** [comment]
Changed the popup message for that. This one looks better and is more smooth.

![image](https://user-images.githubusercontent.com/6165105/61426340-f645a700-a8ce-11e9-8923-2364831b57eb.png)
