### ISSUE TITLE
Accidental click outside the edit character modal should prompt user if changes were made

### ISSUE THREAD

**Issue by therealadamstel** [tyejae/msf-gg-beta-test#23]
On the edit character screen, if there are changes and I accidentally click outside the modal, it would be nice to get a warning instead of closing it. When I was clicking between my emulator and the chrome window, I accidentally lost my progress in filling things out a time or two.

**Comment by tyejae** [comment]
Now has a popup if you click outside and have unsaved changes.
![image](https://user-images.githubusercontent.com/6165105/61425948-7a972a80-a8cd-11e9-9f60-03c9a0d4933f.png)
