### ISSUE TITLE
Alliance search: only some alliances are clickable

### ISSUE THREAD

**Issue by therealadamstel** [tyejae/msf-gg-beta-test#26]
Please see this video:
https://i.imgur.com/RyM0ubh.mp4

When I go to the alliance search screen, only some of the alliances are clickable. The hover does not work, the cursor doesn't change to a hand, and clicking them does nothing. After searching the alliances ("hydra") to limit it to two, the problem is still evident.

OS: Windows 10
Browser: Chrome

**Comment by tyejae** [comment]
Only public alliances can be viewed.

**Comment by tyejae** [comment]
Whoops didn't mean to reopen. 

But yea, only public alliances can be viewed.
