### ISSUE TITLE
Bug: Icon in profile is different in alliance

### ISSUE THREAD

**Issue by AgtWard** [tyejae/msf-gg-beta-test#27]
In profil (Roster tab) Shield Security is selected.
In Alliance tab, an AIM minion is displayed.
![Report1](https://user-images.githubusercontent.com/53042139/61449327-f5575880-a954-11e9-8fe3-8c0bd327ec77.PNG)
![report2](https://user-images.githubusercontent.com/53042139/61449328-f5efef00-a954-11e9-82c3-214c646b4c53.PNG)

**Comment by tyejae** [comment]
FIXED, will be live when I publish next.
![image](https://user-images.githubusercontent.com/6165105/61579976-58fe9480-aac1-11e9-96df-929c8bb2ddee.png)
