### ISSUE TITLE
CSV Import Not Working

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf-gg-beta-test#28]
Unable to import csv into the roster page. Just says fail.

Attached is a zip with two different versions. The first should be the same as the initial export without some of the characters. The second has the name column removed.

[imports.zip](https://github.com/tyejae/msf-gg-beta-test/files/3425109/imports.zip)

**Comment by tyejae** [comment]
Okay this is fixed now. However with the name column removed, it doesn't work because it's expecting the power to start at the 3rd column, so if you just put a blank column it works without the names. I will open up a new bug to have better error handling. But for now you can upload.
