### ISSUE TITLE
Alliance Management

### ISSUE THREAD

**Issue by Kjnava** [tyejae/msf-gg-beta-test#37]
1. After accepting 1 pending invite the page must be refreshed for each on afterwards.
2. I created my alliance but i am not the leader and cannot pass on the leader role to the actual leader. This would be useful even when a leader steps down.

**Comment by tyejae** [comment]
I will fix these ASAP. Thanks 🙏🏻

**Comment by tyejae** [comment]
1. Fixed
2. Fixed
![image](https://user-images.githubusercontent.com/6165105/63193205-af5be600-c021-11e9-9840-79cb496a3471.png)

**Comment by tyejae** [comment]
Will be live shortly
