### ISSUE TITLE
How do I sync my profile? 

### ISSUE THREAD

**Issue by Andrew221091** [tyejae/msf-gg-beta-test#42]
I cannot sync my profile, nor does it find my Alliance. 

I cannot save chars that I updated manually, nor can I update my profile. It shows up "Not authorized to update user info"

I am registered and logged in normally. 

Where is the problem?

**Comment by MrWilson987** [comment]
I am having the same issue. I enter my PID # and nothing happens. Please help us fix this.

**Comment by tyejae** [comment]
@MrWilson987 @Andrew221091 You'll need to simply log out and back in. Sorry for the confusion. Logging out and back in will allow you to make your changes. PM me on Discord or here if this doesn't work. 

@Andrew221091  Your alliance leader just needs to go to the site and sign up. You should be able to then find your alliance. Heck, you could even register the alliance for your alliance. There is no restriction on who does it.
