### ISSUE TITLE
power counts

### ISSUE THREAD

**Issue by PirateKitty** [tyejae/msf-gg-beta-test#59]
I noticed when I was inputting my stats that the total collection power is 3 points off and strongest team power is 2 points off. In the game, my total collection power is 16212 and on the website, it's 16215. My strongest team power in game is 10805 and on site, it's 10807.

**Comment by tyejae** [comment]
This is actually due to the fact that the game **uses** fractions for their power and rounds accordingly. So until they give us an API and I can grab actual powers, we'll have to live with this anomaly.
