### ISSUE TITLE
No me sincroniza mi perfil

### ISSUE THREAD

**Issue by plot2500** [tyejae/msf-gg-beta-test#61]
PID: 26490701

Enter several times, but it doesn't synchronize me with the game.

Greetings and thanks

----------------------------------------------------------------------------------------------

Ingrese varias veces, pero no me sincroniza con el juego.

Saludos y gracias

**Comment by tyejae** [comment]
It does not synchronize with the game yet. FoxNext hasn’t given us that ability. When they do, it will be implemented
