### ISSUE TITLE
Implement Filter System For Roster

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf-gg-beta-test#7]
Integrate a filter system better than the game ;)

**Comment by tyejae** [comment]
Add the same filters than the Characters tab

**Comment by therealadamstel** [comment]
Right now you can work around this by going to characters, setting a filter, then when you go to the roster it's filtered.

**Comment by tyejae** [comment]
![image](https://user-images.githubusercontent.com/6165105/61584255-7bac9f80-aaf9-11e9-8cb7-bfcce32e9c8f.png)
